
package za.ac.cput.guis;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;

/**
 *Chante Lewis
 *StudentDetailsGui.java
 *Due Date: 19 May 2022
 *Subject: Project3
 */
public class StudentDetailsGui extends javax.swing.JFrame {


	/**
	 * Creates new form
	 * StudentDetailsGui
	 */
	public StudentDetailsGui() {
		initComponents();
		Connect();
		Student_Load();
		
	}
	Connection con;
	PreparedStatement pst;
	ResultSet rs;	
	
	//Coonect to database
	public void Connect(){
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentmanage","root","");
			System.out.println("Database is connected.");
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null,"Connection error");
		} catch (ClassNotFoundException ex) {
			JOptionPane.showMessageDialog(null,"Still connecttion error");
		}
	}
	
	//Retrieve data from database and load onto table
	public void Student_Load(){
	    
		try {
			String query = "SELECT * FROM student";
			
			Statement pst = con.createStatement();
			ResultSet rs = pst.executeQuery(query);
			
			String columns[] = { "StudentID", "name", "surname","email_address","course"};
			String data[][] = new String[5][5];
			
			int i = 0;
			while (rs.next()) {
				String id = rs.getString("StudentID");
				String name = rs.getString("name");
				String sname = rs.getString("surname");
				String email = rs.getString("email_address");
				String course = rs.getString("course");
				data[i][0] = id + "";
				data[i][1] = name;
				data[i][2] = sname;
				data[i][3] = email;
				data[i][4] = course;
				i++;
			}
			DefaultTableModel model = new DefaultTableModel(data, columns);
			jTableData.setModel(model);
		} catch(SQLException e) {JOptionPane.showMessageDialog(null, "Errror displaying data!");}

	}
	/**
	 * This method is called from within
	 * the constructor to initialize the
	 * form. WARNING: Do NOT modify this
	 * code. The content of this method
	 * is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStuDetails = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        lblStuDetailsDatabse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblDetailsView = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStuDisplay = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        lblStuDetails.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblStuDetails.setText("Student Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(lblStuDetails)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStuDetails)
                .addGap(18, 18, 18))
        );

        lblStudentID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStudentID.setText("Student ID:");

        lblStuDetailsDatabse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStuDetailsDatabse.setText("Student Details in databse:");

        jTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "StudentID", "name", "surname", "email_address", "course"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableData);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblDetailsView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDetailsView.setText("Searched Student Details:");

        jScrollPane2.setViewportView(txtStuDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentID)
                            .addComponent(lblStuDetailsDatabse))
                        .addGap(11, 11, 11)
                        .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(128, 128, 128)
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetailsView, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentID)
                            .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDetailsView, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblStuDetailsDatabse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnBack)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
		// Code for searching using StudentID
		try {  
           String str = txtStudentID.getText();  
           PreparedStatement st = con.prepareStatement("select * from student where studentid=?");  
           st.setString(1, str);  
            //Excuting Query  
            ResultSet rs = st.executeQuery();  
            if (rs.next()) {  
                String s = rs.getString("StudentID");  
                String s1 = rs.getString("name");  
                String s2 = rs.getString("surname");  
                String s3 = rs.getString("email_address");  
				String s4 = rs.getString("course");  
                //Sets Records in TextFields.  
				txtStuDisplay.setText("Student number: " + s + "\nStudent name: " + s1 + "\nStudent surname: " +s2+ "\nEmail Address: " +s3+ "\nCourse: " +s4); 
            } else {  
                JOptionPane.showMessageDialog(null, "StudentID not found");  
            }  
            //Create Exception Handler  
        } catch (HeadlessException | SQLException ex) {  
            System.out.println(ex);  
        }  
    
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Back button (full action to be implemented when application is integrated)
		 JOptionPane.showMessageDialog(null, "When button clicked it goes to previous GUI");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
		//Code to clear/cancel form
		txtStudentID.setText("");
    	txtStuDisplay.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       // Code to exit system
	   
	  int response = JOptionPane.showConfirmDialog(rootPane, "Would you like to exit?");
	   
	   if(response == JOptionPane.YES_OPTION){
		   System.exit(0);
	   }

    }//GEN-LAST:event_btnExitActionPerformed

    private void jTableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDataMouseClicked
		//Code to select/click data in table and display in textfield
		int row = jTableData.getSelectedRow();
		String tc = jTableData.getModel().getValueAt(row, 0).toString();
		try {  
           PreparedStatement st = con.prepareStatement("select * from student where studentid="+tc+"");  
        //Excuting Query  
            ResultSet rs = st.executeQuery();  		
            if (rs.next()) {  
                String s = rs.getString("StudentID");  
                String s1 = rs.getString("name");  
                String s2 = rs.getString("surname");  
                String s3 = rs.getString("email_address");  
				String s4 = rs.getString("course");  
				   
		//Sets Records in TextFields.  
				txtStuDisplay.setText("Student number: " + s + "\nStudent name: " + s1 + "\nStudent surname: " +s2+ "\nEmail Address: " +s3+ "\nCourse: " +s4); 
            } else {  
                JOptionPane.showMessageDialog(null,"Student does not exist!");  
            }  
            //Create Exception Handler  
        } catch (HeadlessException | SQLException ex) {  
            System.out.println(ex);  
        } 
    }//GEN-LAST:event_jTableDataMouseClicked

	/**
	 * @param args the command line
	 * arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StudentDetailsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StudentDetailsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StudentDetailsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StudentDetailsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentDetailsGui().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableData;
    private javax.swing.JLabel lblDetailsView;
    private javax.swing.JLabel lblStuDetails;
    private javax.swing.JLabel lblStuDetailsDatabse;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JTextPane txtStuDisplay;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
